### ISSUE TITLE
Unable to get Learn to recognize my passing tests from Nitrous

### ISSUE THREAD

**Issue by tyleresmith** [learn-co-curriculum/SQL-bear-organizer-lab#29]
The "Run Local Test" bubble remains grey even after passing the NItrous tests. I've pushed a passing copy for the mean time.

**Comment by AnnJohn** [comment]
hi @tyleresmith sorry for the issue that you're having. Since this is a technical problem, could you use the Ask a Question tool or file a bug report (if you hover over your profile pic in Learn, you'll see an option to report a bug). We're aware of issues with Nitrous and are working on resolving the issue. Thanks!
